

 const GETDATA_req="GETDATA"
 const GETDATASUCCESS_succ='GETDATASUCCESS'
 const GETDATAERROR_err='GETDATAERROR'

 export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
 export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
 export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

 export {GETDATA_req,GETDATAERROR_err,GETDATASUCCESS_succ}